### PR TITLE
Adds #performer and #title methods for main metadata

### PR DESCRIPTION
**Pull request by attilagyorffy**
This pull request adds an extra 2 methods:
- `RubyCue::Cuesheet#performer`
- `RubyCue::Cuesheet#title`

Originally when parsing the first performer and title matches, they were removed. I've added the methods above that can be used to return metadata for the entire cue sheet and not just the individual songs.

### CODE REVIEW

**Comment by blakesmith** [comment]
Looks great, thanks for the addition! Are you doing anything fun with cuesheets?

**Comment by attilagyorffy** [comment]
I am building an app that reads from cue sheets, so your library came quite handy. You also get bonus points for having drum & bass tracks (Netsky) in your fixtures. :P

**Comment by blakesmith** [comment]
Very cool! Let me know how it goes, and if you need any help with anything. Always love to help out a fellow electronica fan. ;-)

**Comment by attilagyorffy** [comment]
I might open source it later, it is still under development and it's just still shaping up. Will send you a shout if you are interested. It's related to DJ mixes mainly.

**Pull request closed without merging**
